import {createRoutine} from "redux-saga-routines";

const GET_TXNS_LIST = createRoutine("GET_TXNS_LIST");
const GET_TXNS_ONE = createRoutine("GET_TXNS_ONE");
const GET_TXNS_REPORT_COUNT = createRoutine("GET_TXNS_REPORT_COUNT");
const GET_TXNS_STATUS_COUNT = createRoutine("GET_TXNS_STATUS_COUNT");
const DOWNLOAD_TXNS_EXCEL_FILE = createRoutine("DOWNLOAD_TXNS_EXCEL_FILE");
const DOWNLOAD_TXNS_PDF_FILE = createRoutine("DOWNLOAD_TXNS_PDF_FILE");
const UPDATE_TXNS_REFUND = createRoutine("UPDATE_TXNS_REFUND");
const UPDATE_TXNS_REPROCESS = createRoutine("UPDATE_TXNS_REPROCESS");
const GET_TXNS_ONE_HISTORY = createRoutine("GET_TXNS_ONE_HISTORY");

export default {
    GET_TXNS_LIST,
    GET_TXNS_ONE,
    DOWNLOAD_TXNS_EXCEL_FILE,
    GET_TXNS_REPORT_COUNT,
    GET_TXNS_STATUS_COUNT,
    DOWNLOAD_TXNS_PDF_FILE,
    UPDATE_TXNS_REFUND,
    UPDATE_TXNS_REPROCESS,
    GET_TXNS_ONE_HISTORY
}
